image:
  repository: artifactory.dagility.com/docker/gh-bs-frontend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: gh-bs-frontend-habitat-development.dagility.com
    paths:
    - /
serviceAccount:
  create: false
